AAD:
  url: http://demoserver:8090/CAST-AAD/rest/
  userName: *****
  password: *****

highlight:
  url: https://rpa.casthighlight.com
  userName: *****  
  password: *****
  defaultDomain: 1111
  allApplDomain: 1697
  allApplDomainName: All
  javaBinFolder: C:/Program Files/Java/jre1.8.0_131/bin
  jar: C:/highlight/HighlightAutomation.jar
  resultsFolder: C:/highlight/ScanResults
  perlFolder: C:/highlight/perl
  proxyHost:  
  proxyPort: 
 
cast:datasource:
  url: jdbc:postgresql://demotest:2280/postgres
  username: *****
  password: *****
  poolsize: 30
  driver: org.postgresql.Driver
 
#logging.level.org.springframework.web: DEBUG
#logging.level.org.springframework.security: DEBUG 

